#define MAXROWS 8
#define MAXCOLS 14
#define GAMEDIMENSION 2

#define MINARGS 5
#define MAX_READ_JSON 255

#define INIT_LIVES 3
#define INIT_BALL_SPEED 2
#define INIT_LVL 1
#define INIT_SCORE 0
#define INIT_RACKET_LEN 300


#define BRICK_LIFE 5
#define BRICK_BALL 6
#define BRICK_SPEED_UP 7
#define BRICK_SPEED_DOWN 8
#define BRICK_RACKET_UP 9
#define BRICK_RACKET_DOWN 10

#define DEFAULT_BUFLEN 512
#define PORT 8080